## **DATA LOADING AND DATA READING:**

In [2]:
import pandas as pd  
data=pd.read_csv(r'C:\Users\zbook\Desktop\Smart study planner project\student_study_habits.csv')
data

,study_hours_per_week,sleep_hours_per_day,attendance_percentage,assignments_completed,final_grade,participation_level_Low,participation_level_Medium,internet_access_Yes,parental_education_High School,parental_education_Master's,parental_education_PhD,extracurricular_Yes,part_time_job_Yes
0,346,409,449,2,431,0,1,1,0,0.0,0,1,0
1,219,487,392,5,216,0,1,1,0,0.0,0,0,0
2,376,36,241,9,285,0,1,1,0,0.0,0,1,0
3,465,351,115,2,320,1,0,1,0,0.0,0,1,0
4,201,115,365,3,133,0,1,1,1,0.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,357,190,450,2,330,0,1,1,1,0.0,0,1,0
496,70,478,450,3,92,1,0,1,1,0.0,0,0,0
497,212,369,431,5,476,0,0,1,1,0.0,0,1,0
498,92,129,408,3,49,0,0,1,1,0.0,0,1,0
499,38,354,349,7,168,1,0,1,0,0.0,0,1,0

## **DATA EXPLORATION:**

In [3]:
data.head()

,study_hours_per_week,sleep_hours_per_day,attendance_percentage,assignments_completed,final_grade,participation_level_Low,participation_level_Medium,internet_access_Yes,parental_education_High School,parental_education_Master's,parental_education_PhD,extracurricular_Yes,part_time_job_Yes
0,346,409,449,2,431,0,1,1,0,0.0,0,1,0
1,219,487,392,5,216,0,1,1,0,0.0,0,0,0
2,376,36,241,9,285,0,1,1,0,0.0,0,1,0
3,465,351,115,2,320,1,0,1,0,0.0,0,1,0
4,201,115,365,3,133,0,1,1,1,0.0,0,1,0

In [4]:
data.tail()

,study_hours_per_week,sleep_hours_per_day,attendance_percentage,assignments_completed,final_grade,participation_level_Low,participation_level_Medium,internet_access_Yes,parental_education_High School,parental_education_Master's,parental_education_PhD,extracurricular_Yes,part_time_job_Yes
495,357,190,450,2,330,0,1,1,1,0.0,0,1,0
496,70,478,450,3,92,1,0,1,1,0.0,0,0,0
497,212,369,431,5,476,0,0,1,1,0.0,0,1,0
498,92,129,408,3,49,0,0,1,1,0.0,0,1,0
499,38,354,349,7,168,1,0,1,0,0.0,0,1,0

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   study_hours_per_week            500 non-null    int64
 1   sleep_hours_per_day             500 non-null    int64
 2   attendance_percentage           500 non-null    int64
 3   assignments_completed           500 non-null    int64
 4   final_grade                     500 non-null    int64
 5   participation_level_Low         500 non-null    int64
 6   participation_level_Medium      500 non-null    int64
 7   internet_access_Yes             500 non-null    int64
 8   parental_education_High School  500 non-null    int64
 9   parental_education_Master's     500 non-null    float64
 10  parental_education_PhD          500 non-null    int64
 11  extracurricular_Yes             500 non-null    int64
 12  part_time_job_Yes               500 non-null    int64
dtypes: float64(1), int64(12)
memory usage: 50.9 KB

In [6]:
print('rows: ', data.shape[0])
print('columns: ', data.shape[1])

rows:  500
columns:  13

In [7]:
data.isnull().sum()

study_hours_per_week              0
sleep_hours_per_day               0
attendance_percentage             0
assignments_completed             0
final_grade                       0
participation_level_Low           0
participation_level_Medium        0
internet_access_Yes               0
parental_education_High School    0
parental_education_Master's       0
parental_education_PhD            0
extracurricular_Yes               0
part_time_job_Yes                 0
dtype: int64

In [8]:
Data=data.fillna(data.mean)
Data=data.fillna(data.median)
Data=data.fillna(data.mode())